---
all:
  vars:
    ansible_user: root

  hosts:
    # not yet managed using Ansible
    #pulp-repo.osci.io:
    www.pulpproject.org:
      ansible_host: 8.43.85.236   # until the DNS is updated

  children:
    cage_zone:
      hosts:
        #pulp-repo.osci.io:
        www.pulpproject.org:

