---
- src: git+https://gitlab.com/osci/ansible-role-selinux.git
  name: selinux
- src: git+https://gitlab.com/osci/ansible-role-openssh.git
  name: openssh
- src: git+https://gitlab.com/osci/ansible-role-entropy.git
  name: entropy
- src: git+https://gitlab.com/osci/ansible-role-guest_virt_tools.git
  name: guest_virt_tools
- src: git+https://gitlab.com/osci/ansible-role-unattended_updates.git
  name: unattended_updates
- src: git+https://gitlab.com/osci/ansible-role-chrony.git
  name: chrony
- src: git+https://gitlab.com/osci/ansible-role-ah-httpd.git
  name: httpd
- src: git+https://gitlab.com/osci/ansible-role-web_builder.git
  name: builder
- src: git+https://gitlab.com/osci/ansible-role-msmtp.git
  name: msmtp

