---

- name: "Create doc builder's user"
  user:
    name: "{{ doc_user }}"
    shell: /usr/bin/rssh
    groups:
      - rsshusers
    comment: "Doc Builder User for {{ component.key }}"

- name: "Create doc component's directory"
  file:
    path: "/var/www/docs.pulpproject.org/{{ component.key }}"
    state: directory
    owner: "{{ doc_user }}"
    group: "{{ doc_user }}"
    mode: "0755"

- name: "Add RSSH config for doc builder's user"
  lineinfile:
    path: /etc/rssh.conf
    state: present
    regexp: '^user\s+=\s+{{ doc_user }}'
    line: "user = {{ doc_user }}:011:10000:"
    owner: root
    group: root
    mode: "0644"

# rsync is already installed for the web builder sync
- name: "Install doc builder's SSH key"
  ansible.posix.authorized_key:
    key: "{{ component.value.ssh_key }}"
    user: "{{ doc_user }}"

